"""Modular PS-GAIL training components."""

from .types import AgentTransition, RolloutBatch
from .torch_utils import SquashedNormal, resolve_device, set_optimizer_lr, _as_device_tensor
from .policy import infer_policy_obs_dim, centralized_critic_enabled, central_critic_observation_dim, infer_critic_obs_dim, infer_continuous_action_dim, _is_continuous, _masked_discrete_logits, policy_action_dim, discrete_action_masks_from_env, _finite_scalar, _vehicle_scalar, _vehicle_origin, central_critic_observations, policy_distribution_and_values, _sample_policy_actions, _actions_to_env_tuple, recurrent_policy_enabled, _memory_storage_dtype, _empty_step_memory, _memory_cache_from_state, _step_memory_to_numpy, _update_memory_state, _recurrent_memory_cache_from_prior_steps, _shift_recurrent_memory, recurrent_memory_stats, policy_distribution_values_memory, _make_policy_from_state_dict
from .evaluation import evaluation_thread_context, _parse_evaluation_horizons, _evaluation_scenarios, _evaluation_episode_names, _make_matched_eval_env, _make_matched_eval_all_vehicle_env, _deterministic_policy_action_tuple, _lane_offset_for_position, _first_controlled_vehicle, _physical_accel_from_action, _physical_accels_from_actions, _matched_eval_metrics, _strip_internal_matched_metrics, _combine_matched_eval_metric_dicts, _chunk_evenly, _policy_input_dim, _cpu_state_dict, _configure_evaluation_worker_threads, _eval_policy_cache_key, _cached_eval_policy, _matched_eval_env_cache_key, _get_matched_eval_env, _matched_eval_worker, _evaluate_policy_matched_all_vehicle_episodes, evaluate_policy_matched_trajectories, _evaluate_policy_matched_trajectories_impl
from .rewards import compute_returns_and_advantages, discriminator_reward, discriminator_input_mode, _transition_array, _metric_float, player_challenge_pressure_from_metric, player_challenge_payoff, player_challenge_bonus, combine_primary_env_challenge_rewards, sequence_rewards_to_transition_rewards, action_conditioned_features, should_normalize_gail_reward, should_apply_gail_reward_clip, safe_normalize_adversarial_rewards, shape_adversarial_rewards, shape_rollout_rewards
from .rollouts import _RolloutPerfProfiler, _actions_to_rollout_array, _assign_psro_sources, _mixed_policy_actions, _target_rollout_episodes, _estimate_controlled_vehicles_for_target, _target_aware_rollout_episodes, refresh_rollout_rewards, collect_rollout, merge_rollout_batches, rollout_training_agent_step_cap, _trajectory_sample_indices, _remap_trajectory_ids, _subset_scene_features, _subset_sequence_features, subsample_rollout_for_training, collect_round_rollouts, _rollout_worker, collect_rollouts, make_rollout_executor, make_evaluation_executor
from .discriminator import _wgan_gradient_penalty, _sample_array_indices, _score_discriminator_candidates, _soft_hard_indices, select_hard_discriminator_examples, update_discriminator
from .ppo import _recurrent_rollout_chunks, _update_recurrent_policy, update_policy

__all__ = [
    'AgentTransition',
    'RolloutBatch',
    'SquashedNormal',
    'resolve_device',
    'set_optimizer_lr',
    '_as_device_tensor',
    'infer_policy_obs_dim',
    'centralized_critic_enabled',
    'central_critic_observation_dim',
    'infer_critic_obs_dim',
    'infer_continuous_action_dim',
    '_is_continuous',
    '_masked_discrete_logits',
    'policy_action_dim',
    'discrete_action_masks_from_env',
    '_finite_scalar',
    '_vehicle_scalar',
    '_vehicle_origin',
    'central_critic_observations',
    'policy_distribution_and_values',
    '_sample_policy_actions',
    '_actions_to_env_tuple',
    'recurrent_policy_enabled',
    '_memory_storage_dtype',
    '_empty_step_memory',
    '_memory_cache_from_state',
    '_step_memory_to_numpy',
    '_update_memory_state',
    '_recurrent_memory_cache_from_prior_steps',
    '_shift_recurrent_memory',
    'recurrent_memory_stats',
    'policy_distribution_values_memory',
    '_make_policy_from_state_dict',
    'evaluation_thread_context',
    '_parse_evaluation_horizons',
    '_evaluation_scenarios',
    '_evaluation_episode_names',
    '_make_matched_eval_env',
    '_make_matched_eval_all_vehicle_env',
    '_deterministic_policy_action_tuple',
    '_lane_offset_for_position',
    '_first_controlled_vehicle',
    '_physical_accel_from_action',
    '_physical_accels_from_actions',
    '_matched_eval_metrics',
    '_strip_internal_matched_metrics',
    '_combine_matched_eval_metric_dicts',
    '_chunk_evenly',
    '_policy_input_dim',
    '_cpu_state_dict',
    '_configure_evaluation_worker_threads',
    '_eval_policy_cache_key',
    '_cached_eval_policy',
    '_matched_eval_env_cache_key',
    '_get_matched_eval_env',
    '_matched_eval_worker',
    '_evaluate_policy_matched_all_vehicle_episodes',
    'evaluate_policy_matched_trajectories',
    '_evaluate_policy_matched_trajectories_impl',
    'compute_returns_and_advantages',
    'discriminator_reward',
    'discriminator_input_mode',
    '_transition_array',
    '_metric_float',
    'player_challenge_pressure_from_metric',
    'player_challenge_payoff',
    'player_challenge_bonus',
    'combine_primary_env_challenge_rewards',
    'sequence_rewards_to_transition_rewards',
    'action_conditioned_features',
    'should_normalize_gail_reward',
    'should_apply_gail_reward_clip',
    'safe_normalize_adversarial_rewards',
    'shape_adversarial_rewards',
    'shape_rollout_rewards',
    '_RolloutPerfProfiler',
    '_actions_to_rollout_array',
    '_assign_psro_sources',
    '_mixed_policy_actions',
    '_target_rollout_episodes',
    '_estimate_controlled_vehicles_for_target',
    '_target_aware_rollout_episodes',
    'refresh_rollout_rewards',
    'collect_rollout',
    'merge_rollout_batches',
    'rollout_training_agent_step_cap',
    '_trajectory_sample_indices',
    '_remap_trajectory_ids',
    '_subset_scene_features',
    '_subset_sequence_features',
    'subsample_rollout_for_training',
    'collect_round_rollouts',
    '_rollout_worker',
    'collect_rollouts',
    'make_rollout_executor',
    'make_evaluation_executor',
    '_wgan_gradient_penalty',
    '_sample_array_indices',
    '_score_discriminator_candidates',
    '_soft_hard_indices',
    'select_hard_discriminator_examples',
    'update_discriminator',
    '_recurrent_rollout_chunks',
    '_update_recurrent_policy',
    'update_policy',
]
